import type { Metadata } from 'next'
import './globals.css'
import { cookies } from 'next/headers'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}
import Providers from './Providers'

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    const cookieStore=cookies()
    const defaultTheme=cookieStore.get('theme')?.value||'dark'
    console.log('🐔🐔🐔',defaultTheme)
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body>
                <Providers defaultTheme={defaultTheme}>{children}</Providers>
            </body>
        </html>
    )
}
